# Generated by Django 5.0.6 on 2024-05-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
