# Generated by Django 5.0.6 on 2024-05-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable3', '0002_remove_turno_paciente_remove_turno_medico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
