# Generated by Django 5.0.6 on 2024-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
